
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.1.105:3002']
        labels:
          service: 'my-service'
          group: 'production'
rule_files:
  - 'alert.rules'