version: '3'

networks: 
  elknetwork:

services:
  elasticsearch:
    container_name: elasticsearch_demo
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    networks: 
      - elknetwork
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
  
  logstash:
    container_name: logstash_demo
    image: docker.elastic.co/logstash/logstash:6.6.1
    ports:
      - 12201:12201/udp
    depends_on: 
      - elasticsearch
    networks: 
      - elknetwork
    volumes: 
      - ./config:/usr/share/logstash/pipeline

  kibana:
    container_name: kibana_demo
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch
    networks: 
      - elknetwork